apiVersion: batch/v1
kind: Job
metadata:
  name: "migration-{{.Values.application.name}}"
spec:
  template:
    metadata:
      labels:
        app: {{.Values.application.name}}
    spec:
      restartPolicy: Never
      containers:
        - name: migration-runner
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          envFrom:
            - configMapRef:
                name: "config-{{.Values.application.name}}"
          command: ["bin/rake", "db:has_been_setup", "&&", "bin/rake", "db:migrate", "||", "bin/rake", "db:setup"]
status: {}
