apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.application.name}}
  name: "worker-{{.Values.application.name}}"
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.application.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.application.name}}
    spec:
      containers:
      - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        name: worker
        imagePullPolicy: {{.Values.image.pullPolicy}}
        envFrom:
          - configMapRef:
              name: "config-{{.Values.application.name}}"
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        command: ["bundle", "exec", "sidekiq"]
status: {}
